version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.2.14
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
